ARG NODE_VERSION=22.22-alpine3.22
FROM node:${NODE_VERSION} AS base

WORKDIR /app

# corepack installs pnpm cleanly
RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN chown -R node:node /app

USER node

RUN pnpm install --frozen-lockfile

COPY --chown=node:node . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]